// Generated by gencpp from file uuv_control_msgs/PoseReach.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_POSEREACH_H
#define UUV_CONTROL_MSGS_MESSAGE_POSEREACH_H

#include <ros/service_traits.h>


#include <uuv_control_msgs/PoseReachRequest.h>
#include <uuv_control_msgs/PoseReachResponse.h>


namespace uuv_control_msgs
{

struct PoseReach
{

typedef PoseReachRequest Request;
typedef PoseReachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseReach
} // namespace uuv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uuv_control_msgs::PoseReach > {
  static const char* value()
  {
    return "ffa2c66b3c6d42e336d8ff2c023e44f2";
  }

  static const char* value(const ::uuv_control_msgs::PoseReach&) { return value(); }
};

template<>
struct DataType< ::uuv_control_msgs::PoseReach > {
  static const char* value()
  {
    return "uuv_control_msgs/PoseReach";
  }

  static const char* value(const ::uuv_control_msgs::PoseReach&) { return value(); }
};


// service_traits::MD5Sum< ::uuv_control_msgs::PoseReachRequest> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::PoseReach > 
template<>
struct MD5Sum< ::uuv_control_msgs::PoseReachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::PoseReach >::value();
  }
  static const char* value(const ::uuv_control_msgs::PoseReachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::PoseReachRequest> should match 
// service_traits::DataType< ::uuv_control_msgs::PoseReach > 
template<>
struct DataType< ::uuv_control_msgs::PoseReachRequest>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::PoseReach >::value();
  }
  static const char* value(const ::uuv_control_msgs::PoseReachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uuv_control_msgs::PoseReachResponse> should match 
// service_traits::MD5Sum< ::uuv_control_msgs::PoseReach > 
template<>
struct MD5Sum< ::uuv_control_msgs::PoseReachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uuv_control_msgs::PoseReach >::value();
  }
  static const char* value(const ::uuv_control_msgs::PoseReachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uuv_control_msgs::PoseReachResponse> should match 
// service_traits::DataType< ::uuv_control_msgs::PoseReach > 
template<>
struct DataType< ::uuv_control_msgs::PoseReachResponse>
{
  static const char* value()
  {
    return DataType< ::uuv_control_msgs::PoseReach >::value();
  }
  static const char* value(const ::uuv_control_msgs::PoseReachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_POSEREACH_H
